### ISSUE TITLE
Folds data is missing

### ISSUE THREAD

**Issue by VladimirShitov** [makotu1208/open-problems-multimodal-3rd-solution#1]
Hey @makotu1208! Thank you for the great solution, and for sharing the code!

In the readme, you point to folds data: https://www.kaggle.com/datasets/mhyodo/open-problems-cite-folds . However, this link throws a 404 error, and I can't find this dataset in your Kaggle profile. Could you please provide it?

**Comment by makotu1208** [comment]
Hi, @VladimirShitov 
Thank you for pointing that out!
I had mistakenly made it private. I have turn on public, could you check it ?

**Comment by VladimirShitov** [comment]
Thank you very much, it works!
